AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda for fetching survey request DB records and injecting requests into Twilio via API

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Environment variables"
        Parameters:
          - 01-SERVER
          - 02-PORT
          - 03-DATABASE
          - 04-DRIVER
          - 05-ACCOUNT
          - 06-PASSWORD
          - 07-TWILIO SID
          - 08-TWILIO AUTH
          - 09-TWILIO NUMBER
    ParameterLabels:
      01SERVER:
        default: "SERVER"
      02PORT:
        default: "PORT"
      03DATABASE:
        default: "DATABASE"
      04DRIVER:
        default: "DRIVER"
      05ACCOUNT:
        default: "ACCOUNT"
      06PASSWORD:
        default: "PASSWORD"
      07TWILIOSID:
        default: "TWILIOSID"
      08TWILIOAUTH:
        default: "TWILIOAUTH"
      09TWILIONUMBER:
        default: "TWILIONUMBER"

Parameters:
  01SERVER:
    Description: Database location, via IP or FQN
    Type: String
  02PORT:
    Description: Port on which the database is accessible.
    Type: String
  03DATABASE:
    Description: Database name
    Type: String
  04DRIVER:
    Description: "Database driver, can be one of the following: 'mssql', 'mysql', 'pg', 'oracle', 'sqlite' or 'websql'"
    Type: String
    AllowedPattern: "mysql|mssql|pg|oracle|sqlite|websql"
  05ACCOUNT:
    Description: Name of an account that has read privileges to the database.
    Type: String
  06PASSWORD:
    Description: The password for ACCOUNT above.
    Type: String
    NoEcho: true
  07TWILIOSID:
    Description: Twilio account SID to call from
    Type: String
  08TWILIOAUTH:
    Description: Authorization string for Twilio account
    Type: String
    NoEcho: true
  09TWILIONUMBER:
    Description: Twilio 'call from' phone number
    Type: String
    NoEcho: true

Globals:
    Function:
        Timeout: 10
        MemorySize: 128
        Runtime: nodejs8.10
        Handler: index.handler

Resources:
    twServerParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twServerParameter
          Description: 'Database location, via IP or FQN'
          Type: String
          Value: !Sub '${01SERVER}' 

    twPortParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twPortParameter
          Description: 'Database port'
          Type: String
          Value: !Sub '${02PORT}' 

    twDatabaseParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twDatabaseParameter
          Description: 'Database name'
          Type: String
          Value: !Sub '${03DATABASE}'

    twDriverParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twDriverParameter
          Description: "Database driver, can be one of the following: 'mssql', 'mysql', 'pg', 'oracle', 'sqlite' or 'websql'"
          Type: String
          Value: !Sub '${04DRIVER}'

    twAccountParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twAccountParameter
          Description: 'Account parameter to store in the paramater store'
          Type: String
          Value: !Sub '${05ACCOUNT}'

    twPasswordParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twPasswordParameter
          Description: 'Database password'
          Type: String
          Value: !Sub '${06PASSWORD}'

    twTwilioSIDParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twTwilioSIDParameter
          Description: 'Twilio SID value'
          Type: String
          Value: !Sub '${07TWILIOSID}'

    twTwilioAUTHParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twTwilioAUTHParameter
          Description: 'Authorization string for Twilio account'
          Type: String
          Value: !Sub '${08TWILIOAUTH}'

    twTwilioNumberParameter:
        Type: AWS::SSM::Parameter
        Properties:
          Name: /revolution11twilio/twTwilioNumberParameter
          Description: "Twilio 'call from' phone number"
          Type: String
          Value: !Sub '${09TWILIONUMBER}'

    twVoiceCallback:
        Description: "API Gateway endpoint URL for Twilio API webhooks"
        Type: AWS::Serverless::Function
        Properties:
            Description: 'Handles twilio callbacks after survey has been initiated.'
            CodeUri: s3://revolution11twilio/twVoiceCallback.zip
            Events:
                TwilioAPI:
                    Type: Api
                    Properties:
                        Path: /twilio/rpc/v1/survey/callback
                        Method: post
            Policies:
              - Statement:
                - Action:
                    - ssm:GetParameter
                  Effect: Allow
                  Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/revolution11twilio/*
            Environment:
              Variables:
                SERVER: !Ref twServerParameter
                PORT: !Ref twPortParameter
                DATABASE: !Ref twDatabaseParameter
                DRIVER: !Ref twDriverParameter
                ACCOUNT: !Ref twAccountParameter
                PASSWORD: !Ref twPasswordParameter
                T_SID: !Ref twTwilioSIDParameter
                T_AUTH: !Ref twTwilioAUTHParameter
                T_NUMBER: !Ref twTwilioNumberParameter

    twVoiceCallRequestExecuteIot:
        Description: "Initiates survey from IoT button and existing survey request (phone# in request is called)."
        Type: AWS::Serverless::Function
        Properties:
            Description: 'Initiates survey from IoT button and existing survey request (phone# in request is called).'
            CodeUri: s3://revolution11twilio/twVoiceCallRequestExecuteIot.zip
            Policies:
              - Statement:
                - Action:
                    - ssm:GetParameter
                  Effect: Allow
                  Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/revolution11twilio/*
            Environment:
              Variables:
                SERVER: !Ref twServerParameter
                PORT: !Ref twPortParameter
                DATABASE: !Ref twDatabaseParameter
                DRIVER: !Ref twDriverParameter
                ACCOUNT: !Ref twAccountParameter
                PASSWORD: !Ref twPasswordParameter
                T_SID: !Ref twTwilioSIDParameter
                T_AUTH: !Ref twTwilioAUTHParameter
                T_NUMBER: !Ref twTwilioNumberParameter
                WEBHOOK_URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}/twilio/rpc/v1/survey/callback"

        

Outputs:

    twServerParameter:
      Description: "Database location, via IP or FQN"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twServerParameter }

    twPortParameter:
      Description: "Database port"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twPortParameter }

    twDriverParameter:
      Description: "Database driver, can be one of the following: 'mssql', 'mysql', 'pg', 'oracle', 'sqlite' or 'websql'"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twDriverParameter }

    twDatabaseParameter:
      Description: "Database name"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twDatabaseParameter }

    twAccountParameter:
      Description: "Database user account name"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twAccountParameter }

    twPasswordParameter:
      Description: "Database password"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twPasswordParameter }

    twTwilioAUTHParameter:
      Description: "Authorization string for Twilio account"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twTwilioAUTHParameter }

    twTwilioSIDParameter:
      Description: "Twilio SID value"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twTwilioSIDParameter }

    twTwilioNumberParameter:
      Description: "Twilio 'call from' phone number"
      Value: !Sub
        - "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${id}/description?region=${AWS::Region}"
        - { id: !Ref twTwilioNumberParameter }

    TwilioApi:
      Description: "API Gateway endpoint URL for Twilio API webhooks"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}/twilio/rpc/v1/survey/callback"

    twVoiceCallback:
      Description: "Handles twilio callbacks after survey has been initiated."
      Value: !GetAtt twVoiceCallback.Arn

    twVoiceCallRequestExecuteIot:
      Description: "Initiates survey from IoT button and existing survey request (phone# in request is called)."
      Value: !GetAtt twVoiceCallRequestExecuteIot.Arn
